Làm việc với thư viện Numpy

In [3]:
import numpy as np

In [12]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # kích thước hàng và cột
print(arr.ndim) # 2 chiều
print(arr.size) #tổng số phần tử
print(arr.dtype) # kiểu dữ lệu
print(arr.itemsize) # kích thước mỗi phần tử

(2, 3)
2
6
int64
8


In [19]:
# ma trận 3 x 4
zeros = np.ones((3,4))
print(zeros)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
# ma trận với giá trị cụ thể
gia_tri = np.full((4,5),7)
print((gia_tri))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [25]:
# ma trận đơn vị là vuông và hàng chéo phải đi qua tâm
don_vi =  np.eye(3)
print(don_vi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
# dãy so tu 0-9
dem_arr = np.arange(10)
print(dem_arr)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
# Bước nhảy
step = np.arange(1,21,2) # từ 1-21 nhảy 2 bước
print(step)

[ 1  3  5  7  9 11 13 15 17 19]


In [29]:
# Chia đều khoảng
chia_khoang = np.linspace(0,1,5)
print(chia_khoang)

[0.   0.25 0.5  0.75 1.  ]


In [31]:
# từ 1D -> 3D

arr1 = np.arange(12)
arr3 = arr1.reshape(2,2,3) # số mảng, hàng , cột

print(arr3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [8]:
# 1. Sử dụng NumPy và regex để trích xuất tất cả số từ một danh sách chuỗi và tạo mảng NumPy chứa các số này.Đầu vào: ["abc 123 def", "45 ghi", "789"]
# Đầu ra: array([123, 45, 789])

import re
import numpy as np

a = ["abc 123 def", "45 ghi", "789"]
number = []
for i in a :
    tim_so = re.findall(r"(\d+)", i)
    number.extend(tim_so)

arr = np.array(number)
print(arr)

['123' '45' '789']


In [ ]:
# 2. Làm việc với mảng 2DMô tả:  Tạo một ma trận 4x4 chứa các số ngẫu nhiên từ 0 đến 9.
# Trích xuất hàng thứ 2 và cột thứ 3 của ma trận.
# Thay thế tất cả các phần tử lớn hơn 5 bằng số 10.



In [12]:
import numpy as np

arr = np.array([4, 7, 9, 10, 5])

mask = arr > 5
print(mask)

filtered = arr[mask]
print(filtered)

print(arr[arr > 5])

[False  True  True  True False]
[ 7  9 10]
[ 7  9 10]


In [23]:
arr = np.array([4, 7, 9, 10, 5])

#AND
result = arr[(arr > 3) & (arr < 8)]
print(result)

#OR
result = arr[(arr < 3) | (arr > 8)]
print(result)

# Thay đổi giá trị thỏa mãn điều kiện
arr[arr>5] = 0
print(arr)

[4 7 5]
[ 9 10]
[4 0 0 0 5]


In [20]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 7]])
# Dùng Flatten() khi bạn muốn đảm bảo mình đang làm việc với 1 bản sao độc lập
flattened = arr2d.flatten()
flattened[1] = 0
print(flattened)
print(arr2d)

# Ravel - Trả về view( nhanh hơn )
# Dùng Ravel() khi bạn ưu tiên hiệu suât và không ngại việc thay đổi  mảng kết quả có thể ảnh hưởng đến mảng gốc

raveled = arr2d.ravel()
raveled[3]=10
print(raveled)
print(arr2d)

[1 0 3 4 5 7]
[[1 2 3]
 [4 5 7]]
[ 1  2  3 10  5  7]
[[ 1  2  3]
 [10  5  7]]


In [41]:
arr1 = np.array([1, 2, 3, 5])
arr2 = np.array([4, 5, 6, 9])

# print(arr1 + arr2)
# print(arr1 - arr2)
# print(arr1 * arr2)
# print(arr1 / arr2)
#
# print(arr1 ** 2)
#
# print(arr1 + 5)
# print(arr1 * 3)

#Ma trận 1 chiều + ma trận 2 chiều
arr3 = np.array([[1, 2, 3, 4],[1, 2, 6, 7]])
res = arr1 + arr3
print(res)

# (3,4) + (4,5) -> ok
# (3,4) + (3,1) -> ok
# (3,4) + (1,4) -> ok
# (3,4) + (2,5) -> ERROR
# (3,4) + (2,4) -> ERROR

[[ 2  4  6  9]
 [ 2  4  9 12]]


In [28]:
# Xử lý NaN

#tạo dữ liệu NaN
data = np.array([1.0, 2.0, np.nan, 4.0, 5.0])
print(data)

# Kiểm tra NaN
nan_mask = np.isnan(data)
print(nan_mask)

#loại bỏ NaN
clean_data = data[~np.isnan(data)]
print(clean_data)

# Thay thế NaN
data_filled = np.nan_to_num(data, nan=3.0)
print(data_filled)

[ 1.  2. nan  4.  5.]
[False False  True False False]
[1. 2. 4. 5.]
[1. 2. 3. 4. 5.]


In [34]:
arr2 = np.array([100, 2000, 30, 40, 50])
res = np.sort(arr2,axis=-1,kind='mergesort')
print(res)

# Vị trí của mảng cũ sau khi sắp xếp
i = np.argsort(arr2)
print(i)


[  30   40   50  100 2000]
[2 3 4 0 1]


In [45]:
data = np.array([100, 2000, 30, 40, 50])

print(f"Tổng = {np.sum(data)}")
print(f"Trung bình = {np.mean(data)}")
print(f"Trung vị = {np.median(data)}")
# Nếu số lượng phần tử là lẻ, trung vị là giá trị ở giữa.
# Nếu số lượng phần tử là chẵn, trung vị là trung bình cộng của hai giá trị giữa.
print(f"Độ lệch chuẩn = {np.std(data)}")
print(f"Phương sai = {np.var(data)}")
# Là trung bình của cả tất cả ((xi-tb)**2)/n
print(f"max = {np.max(data)}")
print(f"min = {np.min(data)}")

Tổng = 2220
Trung bình = 444.0
Trung vị = 50.0
Độ lệch chuẩn = 778.3726613904165
Phương sai = 605864.0
max = 2000
min = 30


In [48]:
import numpy as np
import time
# Sử dụng numpy thay vòng lặp for để cải thiện hiệu suất

large_arr = np.random.random(1_000_000)

def fast_sum(arr):
    return np.sum(arr)

start = time.time()
fast_total = fast_sum(large_arr)
end = time.time()
print(f"Total time = {end - start}")


Total time = 0.0022745132446289062


In [52]:
# Tích vô hướng

arr1 = np.array([[1, 2], [3, 5]])
arr2 = np.array([[4, 5], [6, 9]])

print(arr1 * arr2)
print("\n")

# Nhân ma trận
result = np.matmul(arr1, arr2)
print(result)

# 1 2        3 5
# 4 5        6 9
# Hàng nhân cột :
# 1 * 3 + 2 * 6         1 * 5 + 2 * 9
# 4 * 3 + 5 * 6         4 * 5 +  5 * 9

[[ 4 10]
 [18 45]]


[[16 23]
 [42 60]]


In [139]:
# Ví dụ thực tế - Phân tích dữ liệu học sinh
# Bài toán: Phân tích điểm số học sinh
# Dữ liệu điểm 3 môn của 5 học sinh (Toán, Lý, Hóa)
import numpy as np
scores = np.array([
    [8.5, 7.0, 9.0],  # Học sinh 1
    [9.0, 8.5, 8.0],  # Học sinh 2
    [7.5, 6.5, 7.0],  # Học sinh 3
    [9.5, 9.0, 9.5],  # Học sinh 4
    [6.0, 5.5, 6.5]   # Học sinh 5
])

subjects = ['Toán', 'Lý', 'Hóa']
students = ['An', 'Bình', 'Chi', 'Dũng', 'Hà']
# 1. Điểm trung bình mỗi học sinh
max_score = 0
min_score = 0
max_student = ""
min_student = []

for i in range(len(students)):
    avg = np.mean(scores[i])
    print(f"{students[i]}: {avg:.2f}")

    if avg > max_score:
        max_score = avg
        max_student = students[i]

    if avg <= 7 :
         min_student.append((students[i], avg))


print("\n")
# 2. Điểm trung bình mỗi môn
sub_max = 0
best_subject = ""
for i in range(len(subjects)):
    avg = np.mean(scores[:, i])  # dùng cột
    print(f"{subjects[i]}: {avg:.2f}")

    if avg > sub_max:
        sub_max = avg
        best_subject = subjects[i]

print("\n")
# # 3. Học sinh có điểm cao nhất
print(f"{max_student}: {max_score:.2f}")
print("\n")

# 4. Môn có điểm trung bình cao nhất
print(f"{best_subject}: {sub_max:.2f}")
print("\n")

# 5. Tìm học sinh điểm dưới 7.0
for name, score in min_student:
    print(f"{name}: {score:.2f}")



An: 8.17
Bình: 8.50
Chi: 7.00
Dũng: 9.33
Hà: 6.00


Toán: 8.10
Lý: 7.30
Hóa: 8.00


Dũng: 9.33


Toán: 8.10


Chi: 7.00
Hà: 6.00


In [260]:
# Tạo array 2D (4x3) với các số từ 1 đến 12
arr1 = np.arange(1,13)
arr2d = arr1.reshape(4,3) # số mảng, hàng , cột
print(arr2d)
# Tính tổng mỗi hàng và mỗi cột
tong_hang = arr2d.sum(axis=1)
print("Tổng mỗi hàng:", tong_hang)

tong_cot = arr2d.sum(axis=0)
print("Tổng mỗi cột:", tong_cot)

# Tìm phần tử lớn nhất và vị trí của nó
max = np.max(arr2d)
row_max = 0
col_max = 0

for i in range(arr2d.shape[0]):
    for j in range(arr2d.shape[1]):
         if arr2d[i][j] == max:
            row_max = i
            col_max = j

print(f"Phần tử lớn nhất: {max}")
print(f"Vị trí: dòng {row_max}, cột {col_max}")


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Tổng mỗi hàng: [ 6 15 24 33]
Tổng mỗi cột: [22 26 30]
Phần tử lớn nhất: 12
Vị trí: dòng 3, cột 2


In [160]:
# Cho dữ liệu nhiệt độ 7 ngày trong tuần (độ C)
import numpy as np
temperatures = np.array([25.5, 27.2, 23.8, 29.1, 26.7, 24.3, 28.0])
# 1. Tính nhiệt độ trung bình
def Nhiet_do_trung_binh(arr):
    return np.mean(arr)
kq = Nhiet_do_trung_binh(temperatures)
print("Nhiệt độ trung bình trong tuần:",kq)

# 2. Tìm ngày nóng nhất và lạnh nhất
def Ngay_nong_nhat(arr):
    for i in range(len(arr)):
        kq = np.max(arr)
        ngay = np.argmax(arr) + 1
    print(f"Ngày nóng nhất: Ngày {ngay} với nhiệt độ {kq}°C")
Ngay_nong_nhat(temperatures)

def Ngay_lanh_nhat(arr):
    for i in range(len(arr)):
        kq = np.min(arr)
        ngay = np.argmin(arr) + 1
    print(f"Ngày lạnh nhất: Ngày {ngay} với nhiệt độ {kq}°C")
Ngay_lanh_nhat(temperatures)

# 3. Đếm số ngày nhiệt độ > 26°C
def Dem_so_ngay(arr):
    b = []
    for i in range(len(arr)):
        if arr[i] > 26 :
            b.append(i + 1)
            print(i+1,end=" ")

    print(f"Là {len(b)} ngày có nhiệt độ > 26°C")
Dem_so_ngay(temperatures)

# 4. Chuyển đổi sang độ F (F = C * 9/5 + 32)
def Chuyendoi (arr):
    arr2 = []
    for i in arr:
        f = i * 9/5 + 32
        arr2.append(round(f))
    print(f"{arr2}",end=" ")

Chuyendoi(temperatures)

Nhiệt độ trung bình trong tuần: 26.37142857142857
Ngày nóng nhất: Ngày 4 với nhiệt độ 29.1°C
Ngày lạnh nhất: Ngày 3 với nhiệt độ 23.8°C
2 4 5 7 Là 4 ngày có nhiệt độ > 26°C
[78, 81, 75, 84, 80, 76, 82] 